//! Telex input method: key-map construction and composed-glyph reversal.

use vnkey_engine::input::{KeyEvType, TELEX_MAPPING, VNE_COUNT};

pub(super) fn telex_key_map(bracket_shortcuts: bool) -> [i32; 256] {
    let mut key_map = [KeyEvType::Normal as i32; 256];
    for entry in TELEX_MAPPING {
        if !bracket_shortcuts && matches!(entry.key, b'[' | b']' | b'{' | b'}') {
            continue;
        }
        key_map[entry.key as usize] = entry.action;
        if entry.action < VNE_COUNT {
            let ch = entry.key;
            if ch.is_ascii_lowercase() {
                key_map[ch.to_ascii_uppercase() as usize] = entry.action;
            } else if ch.is_ascii_uppercase() {
                key_map[ch.to_ascii_lowercase() as usize] = entry.action;
            }
        }
    }
    key_map
}

pub(super) fn telex_chars_from_composed(ch: char) -> &'static str {
    match ch {
        'á' => "as",
        'à' => "af",
        'ả' => "ar",
        'ã' => "ax",
        'ạ' => "aj",
        'Á' => "AS",
        'À' => "AF",
        'Ả' => "AR",
        'Ã' => "AX",
        'Ạ' => "AJ",
        'ă' => "aw",
        'ắ' => "aws",
        'ằ' => "awf",
        'ẳ' => "awr",
        'ẵ' => "awx",
        'ặ' => "awj",
        'Ă' => "AW",
        'Ắ' => "AWS",
        'Ằ' => "AWF",
        'Ẳ' => "AWR",
        'Ẵ' => "AWX",
        'Ặ' => "AWJ",
        'â' => "aa",
        'ấ' => "aas",
        'ầ' => "aaf",
        'ẩ' => "aar",
        'ẫ' => "aax",
        'ậ' => "aaj",
        'Â' => "AA",
        'Ấ' => "AAS",
        'Ầ' => "AAF",
        'Ẩ' => "AAR",
        'Ẫ' => "AAX",
        'Ậ' => "AAJ",
        'đ' => "dd",
        'Đ' => "DD",
        'é' => "es",
        'è' => "ef",
        'ẻ' => "er",
        'ẽ' => "ex",
        'ẹ' => "ej",
        'É' => "ES",
        'È' => "EF",
        'Ẻ' => "ER",
        'Ẽ' => "EX",
        'Ẹ' => "EJ",
        'ê' => "ee",
        'ế' => "ees",
        'ề' => "eef",
        'ể' => "eer",
        'ễ' => "eex",
        'ệ' => "eej",
        'Ê' => "EE",
        'Ế' => "EES",
        'Ề' => "EEF",
        'Ể' => "EER",
        'Ễ' => "EEX",
        'Ệ' => "EEJ",
        'í' => "is",
        'ì' => "if",
        'ỉ' => "ir",
        'ĩ' => "ix",
        'ị' => "ij",
        'Í' => "IS",
        'Ì' => "IF",
        'Ỉ' => "IR",
        'Ĩ' => "IX",
        'Ị' => "IJ",
        'ó' => "os",
        'ò' => "of",
        'ỏ' => "or",
        'õ' => "ox",
        'ọ' => "oj",
        'Ó' => "OS",
        'Ò' => "OF",
        'Ỏ' => "OR",
        'Õ' => "OX",
        'Ọ' => "OJ",
        'ô' => "oo",
        'ố' => "oos",
        'ồ' => "oof",
        'ổ' => "oor",
        'ỗ' => "oox",
        'ộ' => "ooj",
        'Ô' => "OO",
        'Ố' => "OOS",
        'Ồ' => "OOF",
        'Ổ' => "OOR",
        'Ỗ' => "OOX",
        'Ộ' => "OOJ",
        'ơ' => "ow",
        'ớ' => "ows",
        'ờ' => "owf",
        'ở' => "owr",
        'ỡ' => "owx",
        'ợ' => "owj",
        'Ơ' => "OW",
        'Ớ' => "OWS",
        'Ờ' => "OWF",
        'Ở' => "OWR",
        'Ỡ' => "OWX",
        'Ợ' => "OWJ",
        'ú' => "us",
        'ù' => "uf",
        'ủ' => "ur",
        'ũ' => "ux",
        'ụ' => "uj",
        'Ú' => "US",
        'Ù' => "UF",
        'Ủ' => "UR",
        'Ũ' => "UX",
        'Ụ' => "UJ",
        'ư' => "uw",
        'ứ' => "uws",
        'ừ' => "uwf",
        'ử' => "uwr",
        'ữ' => "uwx",
        'ự' => "uwj",
        'Ư' => "UW",
        'Ứ' => "UWS",
        'Ừ' => "UWF",
        'Ử' => "UWR",
        'Ữ' => "UWX",
        'Ự' => "UWJ",
        'ý' => "ys",
        'ỳ' => "yf",
        'ỷ' => "yr",
        'ỹ' => "yx",
        'ỵ' => "yj",
        'Ý' => "YS",
        'Ỳ' => "YF",
        'Ỷ' => "YR",
        'Ỹ' => "YX",
        'Ỵ' => "YJ",
        _ => "",
    }
}